# Generated by Django 3.2.8 on 2021-11-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=11)),
                ('transaction_date', models.DateField()),
                ('corporate_id', models.CharField(max_length=4)),
                ('corporate_name', models.CharField(max_length=56)),
                ('platform', models.CharField(max_length=25)),
                ('deal_type', models.CharField(max_length=8)),
                ('direction', models.CharField(max_length=12)),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('base_volume', models.FloatField()),
                ('quote_volume', models.FloatField()),
                ('periods', models.IntegerField()),
                ('near_rate', models.FloatField()),
                ('far_rate', models.FloatField(null=True)),
                ('near_value_date', models.DateTimeField()),
                ('far_value_date', models.DateTimeField(null=True)),
                ('confirmed_at', models.DateTimeField()),
                ('confirmed_by', models.CharField(max_length=30)),
                ('trader_id', models.CharField(max_length=10)),
                ('trader_name', models.CharField(max_length=20)),
                ('transaction_purpose', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
