# Generated by Django 3.2.8 on 2021-11-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvasapi', '0002_auto_20211108_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='far_rate',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='far_value_date',
            field=models.CharField(default=0, max_length=15, null=True),
        ),
    ]
