# Generated by Django 3.2.8 on 2021-11-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvasapi', '0003_auto_20211108_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='far_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='far_value_date',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
