# Generated by Django 3.2.8 on 2021-11-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvasapi', '0005_auto_20211111_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='http_status_desc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
