# Generated by Django 3.2.8 on 2021-11-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvasapi', '0006_transaction_http_status_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='last_posted_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
